// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sprint05_API_Cidade;

namespace FilmesApi.Migrations
{
//    [DbContext(typeof(CidadeContexto))]
//    partial class CidadeContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder.ApplyConfiguration(new CidadeConfiguration());
//            modelBuilder.ApplyConfiguration(new ClienteConfiguration());
//#pragma warning restore 612, 618
//        }
//    }
}
